spring:
  application:
    name: Universal Directory Constructor
  datasource:
    url: jdbc:postgresql://localhost:5432/Universal+Directory+Constructor
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: debug
    show-sql: true